project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/item-table/
  title: "Item-Tabelle"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/item-table/
  navbar:
    pinned: true
    background: primary
    search: true
    logo: iqb-logo-grey.png
  page-footer:
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - text: "{{< fa house >}}"
        href: index.qmd    

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
